package com.atelierjlg.fern.ui.widgets

import androidx.compose.ui.graphics.Color

// FICHIER GÉNÉRÉ par design/tools/chat_sprites.py : modifier le script plutôt que ce fichier.

/**
 * Le chat de Jules, d'après sa photo : écaille de tortue (brun très foncé marbré de caramel),
 * yeux verts, pattes claires. Un caractère = un pixel (« . » = transparent).
 */
object CatSprites {
    /** Ses vraies couleurs (pas celles du thème : c'est son pelage !). */
    val palette = mapOf(
        'b' to Color(0xFF3B2A22),
        'k' to Color(0xFF1F1612),
        'o' to Color(0xFFA8703F),
        'l' to Color(0xFFC99A63),
        's' to Color(0xFF271B16),
        'p' to Color(0xFFD98C8C),
        'r' to Color(0xFFC76F78),
        'e' to Color(0xFF8FC46A),
        'n' to Color(0xFF14100C),
        'W' to Color(0xFFF4EEDD),
        'd' to Color(0xFF120D0A),
        'w' to Color(0xFFE8DCC6),
    )

    val heartPalette = mapOf(
        'h' to Color(0xFFEC9AA0),
        'H' to Color(0xFFF7D4D6),
    )

    /** Assis, yeux ouverts. */
    val sitA = listOf(
        ".........b............k...........",
        "........bbb..........kkb..........",
        "........bppb........bppb..........",
        "........bppbb......bbppb..........",
        "........bpppbbbkkbbopppb..........",
        "........bpbbobbkkbbooopb..........",
        ".......bbbbbobbbbbbooobbb.........",
        ".......obboloobboobbbobkk.........",
        ".......bbbbolobboobbbbbkk.........",
        ".......boobbobbbooobobbkk.........",
        ".......oolbenWbooooenWbbk.........",
        ".......loleeneeoooeeneebk.........",
        ".......ooobeneboobbenebbb.........",
        ".......boobbbboooobkkbbbb.........",
        ".......oobbkkblooobbbbbbb.........",
        "........obbbbbopppbbbbbb..........",
        ".........lbbbboopobbbbb...........",
        "..........bbbbbdodobbb............",
        "..........oobbbooobbkk............",
        ".........bolooooloobbbb.....oo....",
        ".........kbooooolooobbb.....ool...",
        ".........boooooooobbkkb.....oobb..",
        "........bblloobbbbbkkkkb.....bbb..",
        ".......obboloobbbkkkkbbkk....bbb..",
        ".......obboooobkkkkkbbkkk....bbbo.",
        "......oloooollobbbbbbbkkkk...bbbo.",
        "......oobbbblobbkkbkbbkkkk...bbol.",
        "......oobbkbobbkkkkkkbbkkk...oboo.",
        "......oobbbbbbkkkkkkkbkkkk...olol.",
        "......olbbbbbbkkkkkkkkkkkk...lllo.",
        "......oobbbkkkbkkbbkkkbbbb...bbbo.",
        "......oobbbkkkbbbbbkkbbbob..kkkb..",
        "......ooobbkkkbbbbbbbollob.kkkbb..",
        ".......ooobkkkbbbbbbboooobbkkkb...",
        ".......olobbkkboooobbbbbbbbbbbo...",
        "........lobkkkboooobbbbkkbbboo....",
        ".........obkkkkolobkkkkkkkkb......",
        ".........ssssssssssssssssb........",
        ".........swwww....swwww...........",
        "..........wwww.....boo............",
    )

    /** Assis, clignement (queue de l'autre côté). */
    val sitB = listOf(
        ".........b............k...........",
        "........bbb..........kkb..........",
        "........bppb........bppb..........",
        "........bppbb......bbppb..........",
        "........bpppbbbkkbbopppb..........",
        "........bpbbobbkkbbooopb..........",
        ".......bbbbbobbbbbbooobbb.........",
        ".......obboloobboobbbobkk.........",
        ".......bbbbolobboobbbbbkk.........",
        ".......boobbobbbooobobbkk.........",
        ".......oolbbbbboooobbbbbk.........",
        ".......loldkkkdooodbkkdbk.........",
        ".......ooodddddoobdddddbb.........",
        ".......boobbbboooobkkbbbb.........",
        ".......oobbkkblooobbbbbbb.........",
        "........obbbbbopppbbbbbb..........",
        ".........lbbbboopobbbbb...........",
        "..........bbbbbdodobbb............",
        "..........oobbbooobbkk............",
        ".........bolooooloobbbb...........",
        ".........kbooooolooobbb...........",
        ".........boooooooobbkkb.........ob",
        "........bblloobbbbbkkkkb........ob",
        ".......obboloobbbkkkkbbkk.......ob",
        ".......obboooobkkkkkbbkkk.......ob",
        "......oloooollobbbbbbbkkkk......oo",
        "......oobbbblobbkkbkbbkkkk.....olo",
        "......oobbkbobbkkkkkkbbkkk.....ool",
        "......oobbbbbbkkkkkkkbkkkk.....oll",
        "......olbbbbbbkkkkkkkkkkkk.....lol",
        "......oobbbkkkbkkbbkkkbbbb....bboo",
        "......oobbbkkkbbbbbkkbbbob....kbbb",
        "......ooobbkkkbbbbbbbollob...kbbb.",
        ".......ooobkkkbbbbbbboooo..kkkbbb.",
        ".......olobbkkboooobbbbbbbbbbbob..",
        "........lobkkkboooobbbbkkbbbooo...",
        ".........obkkkkolobkkkkkkkkboo....",
        ".........ssssssssssssssssbbo......",
        ".........swwww....swwww...........",
        "..........wwww.....boo............",
    )

    /** Nourri, content : yeux en ^, joues roses. */
    val happyA = listOf(
        ".........b............k...........",
        "........bbb..........kkb..........",
        "........bppb........bppb..........",
        "........bppbb......bbppb..........",
        "........bpppbbbkkbbopppb..........",
        "........bpbbobbkkbbooopb..........",
        ".......bbbbbobbbbbbooobbb.........",
        ".......obboloobboobbbobkk.........",
        ".......bbbbolobboobbbbbkk.........",
        ".......boobbobbbooobobbkk.........",
        ".......oolbbddboooobddbbk.........",
        ".......lolbdkkdoooodkkdbk.........",
        ".......ooodbkbbdobdkkbbdb.........",
        ".......boobbbboooobkkbbbb.........",
        ".......oobrrkblooobbbrrbb.........",
        "........obbbbbopppbbbbbb..........",
        ".........lbbbboopobbbbb...........",
        "..........bbbbbdodobbb............",
        "..........oobbbooobbkk............",
        ".........bolooooloobbbb.....oo....",
        ".........kbooooolooobbb.....ool...",
        ".........boooooooobbkkb.....oobb..",
        "........bblloobbbbbkkkkb.....bbb..",
        ".......obboloobbbkkkkbbkk....bbb..",
        ".......obboooobkkkkkbbkkk....bbbo.",
        "......oloooollobbbbbbbkkkk...bbbo.",
        "......oobbbblobbkkbkbbkkkk...bbol.",
        "......oobbkbobbkkkkkkbbkkk...oboo.",
        "......oobbbbbbkkkkkkkbkkkk...olol.",
        "......olbbbbbbkkkkkkkkkkkk...lllo.",
        "......oobbbkkkbkkbbkkkbbbb...bbbo.",
        "......oobbbkkkbbbbbkkbbbob..kkkb..",
        "......ooobbkkkbbbbbbbollob.kkkbb..",
        ".......ooobkkkbbbbbbboooobbkkkb...",
        ".......olobbkkboooobbbbbbbbbbbo...",
        "........lobkkkboooobbbbkkbbboo....",
        ".........obkkkkolobkkkkkkkkb......",
        ".........ssssssssssssssssb........",
        ".........swwww....swwww...........",
        "..........wwww.....boo............",
    )

    /** Nourri, queue de l'autre côté. */
    val happyB = listOf(
        ".........b............k...........",
        "........bbb..........kkb..........",
        "........bppb........bppb..........",
        "........bppbb......bbppb..........",
        "........bpppbbbkkbbopppb..........",
        "........bpbbobbkkbbooopb..........",
        ".......bbbbbobbbbbbooobbb.........",
        ".......obboloobboobbbobkk.........",
        ".......bbbbolobboobbbbbkk.........",
        ".......boobbobbbooobobbkk.........",
        ".......oolbbddboooobddbbk.........",
        ".......lolbdkkdoooodkkdbk.........",
        ".......ooodbkbbdobdkkbbdb.........",
        ".......boobbbboooobkkbbbb.........",
        ".......oobrrkblooobbbrrbb.........",
        "........obbbbbopppbbbbbb..........",
        ".........lbbbboopobbbbb...........",
        "..........bbbbbdodobbb............",
        "..........oobbbooobbkk............",
        ".........bolooooloobbbb...........",
        ".........kbooooolooobbb...........",
        ".........boooooooobbkkb.........ob",
        "........bblloobbbbbkkkkb........ob",
        ".......obboloobbbkkkkbbkk.......ob",
        ".......obboooobkkkkkbbkkk.......ob",
        "......oloooollobbbbbbbkkkk......oo",
        "......oobbbblobbkkbkbbkkkk.....olo",
        "......oobbkbobbkkkkkkbbkkk.....ool",
        "......oobbbbbbkkkkkkkbkkkk.....oll",
        "......olbbbbbbkkkkkkkkkkkk.....lol",
        "......oobbbkkkbkkbbkkkbbbb....bboo",
        "......oobbbkkkbbbbbkkbbbob....kbbb",
        "......ooobbkkkbbbbbbbollob...kbbb.",
        ".......ooobkkkbbbbbbboooo..kkkbbb.",
        ".......olobbkkboooobbbbbbbbbbbob..",
        "........lobkkkboooobbbbkkbbbooo...",
        ".........obkkkkolobkkkkkkkkboo....",
        ".........ssssssssssssssssbbo......",
        ".........swwww....swwww...........",
        "..........wwww.....boo............",
    )

    /** L'étirement du matin (de profil). */
    val stretch = listOf(
        ".........................................oobk.",
        ".........................................lbb..",
        "........................................obbb..",
        ".......................................bbbb...",
        ".......b..............................kbbbb...",
        ".......bb.......kb...................kbbbk....",
        ".......bbb......bb..................kbbbb.....",
        ".......opbo.....ob..................bllo......",
        ".......bppbo...bobbbbbbkkkk........bboll......",
        ".......bppb....bbbbbobbkkbbbbb....bbobb.......",
        ".......oplbbbbbooobbbbbbkkbobbbkk.kbbbb.......",
        ".......lolbkkkbooobbkkkbkkbobbbbbkkkbb........",
        ".......ooobbkobooobkkbbbbbbooobbbkkkk.........",
        "......bboobboolooobkkbbbbbboobbbbkkkk.........",
        "......ooobbkolloooobbbbbbbbbbbbbbbbbbb........",
        "......obobbollloooobbbbbbbkkkbboobbbbo........",
        "......bbldddllodddbbbbbobbkkbbolooooloo.......",
        "......bboobllllooobbbbboobkkbbooooooooo.......",
        "......oobbooollooobbkkbooobbooooooooooo.......",
        ".......bkbolppooloobbbboooooooloooobbo........",
        "........kkblrrooloo...bbbolloolobbobbo........",
        ".........boooooooob......blloobbobbbooo.......",
        ".......kbblloobbbbb..........bbbobbbbbb.......",
        ".....ooobboloobbbkk..........bbbo.kkkbb.......",
        "...ooooobboooobkk............bbbo.kkkkb.......",
        ".kbbbboloooollo..............bbbo.bkkkk.......",
        ".kkbbboobbbblo...............bbol.obkkb.......",
        ".kkkbooobbkb.................oboo.lbbbbb......",
        ".wwwwboobb...................olol.lbbbbo......",
        "....wwww.....................lllo..bbkb.......",
    )

    /** Endormi, roulé en boule. */
    val sleep = listOf(
        "............................................",
        "......b.........o...........................",
        "......bb.......bb...........................",
        "......bbb......bpb..........................",
        "......ppbb.....kpb..........................",
        ".....opppbb...bkppb.........................",
        ".....opppbbbobbbb.booobbbbkkbbbb............",
        ".....opobboloobbobbbbobkkbkkkkbkkbb.........",
        ".....lobbbbolobbobbbbbbkkkkbbbkkkkbbb.......",
        ".....bbboobbollbbbbbobbkkbbbbbkkkkbbob......",
        "....bbooolbbbllloobbbbbbkkbobbbkkkkbbbb.....",
        "....bbololbkollloobbkkkbkkbobbbbbkkkbbbb....",
        "....bbdooodoodooodbkkbbbbbbooobbbkkkkkkk....",
        "....bbbdddbooodddobkkbbbbbboobbbbkkkkbkkk...",
        "....boooobboolloooobbbbbbbbbbbbbbbbbbbbob...",
        "....ooobobbollloooobbbbbbbkkkbboobbbboooo...",
        ".....obblllpploooobbbbbobbkkbboloooolooboo..",
        "......bboolllbbooobbbbboobkkbbooooooooobbo..",
        ".......obbooobbooobbkkbooobbooooooooooobbbb.",
        "......bbkbolooooloobbbboooooooloooobboobbbb.",
        ".....obkkkbooooolooobbbbbolloolobbobbookbb..",
        ".....obkkboooooooobbkkbbbblloobbobbbooobbb..",
        "......wwwwlloobbbbbkkkkbbbbbbbbbobbbbbbbb...",
        ".........bolossssssssssssssssssssssssssb....",
        "............sssssssssssssssssssssssssss.....",
        ".................bbssssssssssssssobk........",
    )

    /** Le petit cœur. */
    val heart = listOf(
        "..hh...hh..",
        ".hhhh.hhhh.",
        "hhHHhhhhhhh",
        "hhHhhhhhhhh",
        ".hhhhhhhhh.",
        "..hhhhhhh..",
        "...hhhhh...",
        "....hhh....",
        "....hhh....",
        "...........",
    )
}
